# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(default='Unnamed', max_length=40),
        ),
    ]
