# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bucketlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 16, 11, 52, 28, 16101, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
